# Default values for llm-api
replicaCount: 2

image:
  repository: llmops/api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application specific configuration
app:
  logLevel: "INFO"
  rateLimiting:
    enabled: true
    requestsPerMinute: 60
  
  security:
    cors:
      allowedOrigins: ["*"]
    jwt:
      secretKey: ""  # Set this via secrets
      tokenExpireMinutes: 30

# Environment variables to be set in the container
env:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: llm-api-secrets
        key: openai-api-key
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: llm-api-secrets
        key: jwt-secret-key

# Monitoring and logging configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
  
logging:
  enabled: true
  elasticsearch:
    enabled: true
    host: "elasticsearch-master"
    port: 9200
  fluentd:
    enabled: true
    tag: "llm-api"
