apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "llm-api.fullname" . }}-network-policy
  labels:
    {{- include "llm-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "llm-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow inbound traffic from services in the same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    # Allow monitoring/metrics collection (if enabled)
    {{- if .Values.monitoring.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow outbound traffic to OpenAI API
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    # Allow logging to Elasticsearch (if enabled)
    {{- if .Values.logging.elasticsearch.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: logging
        - podSelector:
            matchLabels:
              app: elasticsearch
      ports:
        - protocol: TCP
          port: {{ .Values.logging.elasticsearch.port }}
    {{- end }}
